services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gasopay-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-gasopay}
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - gasopay-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: gasopay-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-gasopay}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_INITDB_SKIP_TZINFO: "1"
      TZ: "UTC"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - gasopay-network
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-secret}", "--protocol=tcp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: gasopay-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - gasopay-network
    depends_on:
      - app
      - db

networks:
  gasopay-network:
    name: gasopay-network
    driver: bridge

volumes:
  dbdata:
    name: gasopay-dbdata 