services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gasopay-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-gasopay}
      - DB_USERNAME=${DB_USERNAME:-gasopay}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - gasopay-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: gasopay-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-gasopay}
      POSTGRES_USER: ${DB_USERNAME:-gasopay}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      TZ: "UTC"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gasopay-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-gasopay} -d ${DB_DATABASE:-gasopay}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: gasopay-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - gasopay-network
    depends_on:
      - app
      - db

networks:
  gasopay-network:
    name: gasopay-network
    driver: bridge

volumes:
  pgdata:
    name: gasopay-pgdata 